
export const FETCH_PERSON  = 'FETCH_PERSON';
export const FETCH_PERSONS = 'FETCH_PERSONS';
export const CREATE_PERSON = 'CREATE_PERSON';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const DELETE_PERSON = 'DELETE_PERSON';

export const FETCH_COMPANY   = 'FETCH_COMPANY';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const UPDATE_COMPANY  = 'UPDATE_COMPANY';
export const CREATE_COMPANY  = 'CREATE_COMPANY';
export const DELETE_COMPANY  = 'DELETE_COMPANY';